version: '3.3'

services: 
   db:
     image: mysql:5.7
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: servicemysql
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpresspass

   wordpress:
      image: wordpress:latest
      depends_on:
        - db
      ports:
        - "8080:80"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpresspass

volumes:
   db_data:
      external:
         name: database_data
